/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import DAO.UserDAO;
import javax.swing.JOptionPane;
import model.User;

/**
 *
 * @author user1
 */
public class Editar extends javax.swing.JInternalFrame {

    /**
     * Creates new form Editar
     */
    public Editar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        confirmar_botao = new javax.swing.JButton();
        userName_campoRedSenha = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        redefinirSenha_campoRedSenha = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Redefinir Senha");

        confirmar_botao.setText("Confirmar");
        confirmar_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmar_botaoActionPerformed(evt);
            }
        });

        userName_campoRedSenha.setText("Nome de usuário");
        userName_campoRedSenha.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        userName_campoRedSenha.setDoubleBuffered(true);
        userName_campoRedSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userName_campoRedSenhaActionPerformed(evt);
            }
        });

        jLabel1.setText("User");

        jLabel2.setText("Senha Nova");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addComponent(confirmar_botao)
                .addGap(115, 115, 115))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userName_campoRedSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .addComponent(redefinirSenha_campoRedSenha))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(userName_campoRedSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(redefinirSenha_campoRedSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(confirmar_botao)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmar_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmar_botaoActionPerformed
        
        String userName = userName_campoRedSenha.getText().trim();
        String senha = redefinirSenha_campoRedSenha.getText().trim();
                
        try {
            UserDAO userDAO = new UserDAO();
            userDAO.redefinirSenha(userName, senha);
            this.dispose();
            JOptionPane.showMessageDialog(null, "Senha atualizada com sucesso!", "Redefinir Senha", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao redefinir senha", "Redefinir Senha", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_confirmar_botaoActionPerformed

    private void userName_campoRedSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userName_campoRedSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userName_campoRedSenhaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmar_botao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField redefinirSenha_campoRedSenha;
    private javax.swing.JTextField userName_campoRedSenha;
    // End of variables declaration//GEN-END:variables
}
