/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import model.User;
import DAO.UserDAO;

/**
 *
 * @author user1
 */
public class Excluir extends javax.swing.JInternalFrame {

    /**
     * Creates new form Excluir
     */
    public Excluir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        excluir_botao = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        user_campo = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Excluir");

        excluir_botao.setText("Excluir");
        excluir_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluir_botaoActionPerformed(evt);
            }
        });

        jLabel1.setText("User");

        user_campo.setText("Nome do usuário");
        user_campo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_campoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(user_campo, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(excluir_botao)
                .addGap(140, 140, 140))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(user_campo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(excluir_botao)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void excluir_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluir_botaoActionPerformed
        String userCampo = user_campo.getText().trim();
                
        if (userCampo.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo", "Excluir Conta", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            UserDAO userDAO = new UserDAO();
            userDAO.excluirUsuario(userCampo);
            JOptionPane.showMessageDialog(null, "Exclusão realizada com sucesso!", "Excluir Conta", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao excluir", "Excluir Conta", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_excluir_botaoActionPerformed

    private void user_campoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_campoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_campoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton excluir_botao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField user_campo;
    // End of variables declaration//GEN-END:variables
}
