/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import DAO.UserDAO;
import javax.swing.JOptionPane;
import model.User;

/**
 *
 * @author user1
 */
public class Login extends javax.swing.JInternalFrame {

    /**
     * Creates new form Login
     */
    Simulador simulador;
    
    private Principal telaPrincipal;
    public Login(Principal telaPrincipal) {
        initComponents();
        this.telaPrincipal = telaPrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userName_campoLogin = new javax.swing.JTextField();
        password_campoLogin = new javax.swing.JTextField();
        entrar_botao = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setClosable(true);
        setIconifiable(true);
        setTitle("Login");

        jLabel1.setText("User");

        jLabel3.setText("Senha");

        entrar_botao.setText("Entrar");
        entrar_botao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entrar_botaoMouseClicked(evt);
            }
        });
        entrar_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrar_botaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(password_campoLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                            .addComponent(userName_campoLogin)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(entrar_botao)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userName_campoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password_campoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(entrar_botao)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entrar_botaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrar_botaoMouseClicked
        String userCampo = userName_campoLogin.getText().trim(); //Trim retira espaços em branco da String
        String passwordCampo = password_campoLogin.getText().trim();
        
        if (userCampo.isEmpty() || passwordCampo.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha os campos", "Login", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        User user = new User();
        user.setUser(userCampo);
        user.setPassword(passwordCampo);
        
        UserDAO userDAO = new UserDAO();        
        boolean loginValido = userDAO.consultarLogin(user, userCampo, passwordCampo);

	if (loginValido) {
    	    JOptionPane.showMessageDialog(null, "Login realizado com sucesso!", "Login", JOptionPane.INFORMATION_MESSAGE);
            telaPrincipal.getSimuladorMenuItem().setEnabled(true);
            telaPrincipal.getGerenciarMenuItem().setEnabled(true);
            this.dispose();
	} else {
            JOptionPane.showMessageDialog(null, "Login inexistente\nRealize um cadastro", "Login", JOptionPane.INFORMATION_MESSAGE);
	}
        
    }//GEN-LAST:event_entrar_botaoMouseClicked

    private void entrar_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrar_botaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entrar_botaoActionPerformed

    public boolean verificarLogin(){
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton entrar_botao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField password_campoLogin;
    private javax.swing.JTextField userName_campoLogin;
    // End of variables declaration//GEN-END:variables
}
