package view;

import javax.swing.JOptionPane;
import model.User;


public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */   
    public Principal() {
        initComponents();
        simuladorMenuItem.setEnabled(false);
        gerenciarMenuItem.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        executarCadastrar = new javax.swing.JMenu();
        loginMenu = new javax.swing.JMenu();
        simuladorMenuItem = new javax.swing.JMenu();
        simularMenuItem = new javax.swing.JMenuItem();
        gerenciarMenuItem = new javax.swing.JMenu();
        editorMenuItem = new javax.swing.JMenuItem();
        excluirMenuItem = new javax.swing.JMenuItem();
        sairSistema = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(0, 102, 102));
        desktopPane.setForeground(new java.awt.Color(0, 0, 0));

        executarCadastrar.setText("Cadastrar");
        executarCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                executarCadastrarMouseClicked(evt);
            }
        });
        menuBar.add(executarCadastrar);

        loginMenu.setText("Login");
        loginMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMenuMouseClicked(evt);
            }
        });
        menuBar.add(loginMenu);

        simuladorMenuItem.setText("Simulador");
        simuladorMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simuladorMenuItemMouseClicked(evt);
            }
        });
        simuladorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simuladorMenuItemActionPerformed(evt);
            }
        });

        simularMenuItem.setText("Simular");
        simularMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simularMenuItemMouseClicked(evt);
            }
        });
        simularMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simularMenuItemActionPerformed(evt);
            }
        });
        simuladorMenuItem.add(simularMenuItem);

        menuBar.add(simuladorMenuItem);

        gerenciarMenuItem.setText("Gerenciar");

        editorMenuItem.setText("Editar Senha");
        editorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editorMenuItemActionPerformed(evt);
            }
        });
        gerenciarMenuItem.add(editorMenuItem);

        excluirMenuItem.setText("Excluir Conta");
        excluirMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirMenuItemActionPerformed(evt);
            }
        });
        gerenciarMenuItem.add(excluirMenuItem);

        menuBar.add(gerenciarMenuItem);

        sairSistema.setText("Sair");
        sairSistema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairSistemaMouseClicked(evt);
            }
        });
        sairSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairSistemaActionPerformed(evt);
            }
        });
        menuBar.add(sairSistema);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairSistemaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sairSistemaActionPerformed

    private void sairSistemaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairSistemaMouseClicked
        System.exit(0);
    }//GEN-LAST:event_sairSistemaMouseClicked

    private void executarCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_executarCadastrarMouseClicked
        Cadastro cadastrar = new Cadastro();
        desktopPane.add(cadastrar);
        cadastrar.setVisible(true);
    }//GEN-LAST:event_executarCadastrarMouseClicked

    private void simuladorMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simuladorMenuItemMouseClicked
        
    }//GEN-LAST:event_simuladorMenuItemMouseClicked

    private void editorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editorMenuItemActionPerformed
        Editar editor = new Editar();
        desktopPane.add(editor);
        editor.setVisible(true);
    }//GEN-LAST:event_editorMenuItemActionPerformed

    private void excluirMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirMenuItemActionPerformed
        Excluir exclusor = new Excluir();
        desktopPane.add(exclusor);
        exclusor.setVisible(true);
    }//GEN-LAST:event_excluirMenuItemActionPerformed

    private void simuladorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simuladorMenuItemActionPerformed
        
    }//GEN-LAST:event_simuladorMenuItemActionPerformed

    private void loginMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMenuMouseClicked
        Login login = new Login(this);
        desktopPane.add(login);
        login.setVisible(true);
    }//GEN-LAST:event_loginMenuMouseClicked

    private void simularMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simularMenuItemMouseClicked
        
    }//GEN-LAST:event_simularMenuItemMouseClicked

    private void simularMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simularMenuItemActionPerformed
        Simulador sim = new Simulador();
        desktopPane.add(sim);
        sim.setVisible(true);
    }//GEN-LAST:event_simularMenuItemActionPerformed

    public javax.swing.JMenu getSimuladorMenuItem() {
        return simuladorMenuItem;
    }
    
    public javax.swing.JMenu getGerenciarMenuItem() {
        return gerenciarMenuItem;
    }
    
    public javax.swing.JMenu getLoginMenu(){
        return loginMenu;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem editorMenuItem;
    private javax.swing.JMenuItem excluirMenuItem;
    private javax.swing.JMenu executarCadastrar;
    private javax.swing.JMenu gerenciarMenuItem;
    private javax.swing.JMenu loginMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu sairSistema;
    private javax.swing.JMenu simuladorMenuItem;
    private javax.swing.JMenuItem simularMenuItem;
    // End of variables declaration//GEN-END:variables

}
