package view;

import DAO.UserDAO;
import java.util.Locale;
import javax.swing.JOptionPane;
import model.*;

public class Simulador extends javax.swing.JInternalFrame {

    /**
     * Creates new form Simulador
     */
    public Simulador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        valorSimular_campo = new javax.swing.JTextField();
        simular_botao = new javax.swing.JButton();
        userName_campoSim = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Simulador");

        jLabel1.setText("Insira o valor a ser simulado");

        valorSimular_campo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorSimular_campoActionPerformed(evt);
            }
        });

        simular_botao.setText("Simular");
        simular_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simular_botaoActionPerformed(evt);
            }
        });

        userName_campoSim.setText("Fulano");
        userName_campoSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userName_campoSimActionPerformed(evt);
            }
        });

        jLabel2.setText("Insira seu usuário");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(simular_botao)
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(valorSimular_campo)
                            .addComponent(userName_campoSim)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel2)))
                        .addGap(45, 45, 45))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userName_campoSim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valorSimular_campo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(simular_botao)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valorSimular_campoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorSimular_campoActionPerformed
        
    }//GEN-LAST:event_valorSimular_campoActionPerformed

    private void simular_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simular_botaoActionPerformed
        String userCampo = userName_campoSim.getText().trim();
        String valorSTR = valorSimular_campo.getText().trim();
        double valor_simulado = Double.parseDouble(valorSTR);
        
//        if (valorSTR.isEmpty()) {
//            JOptionPane.showMessageDialog(null, "Preencha o campo", "Erro", JOptionPane.INFORMATION_MESSAGE);
//            return;
//        }
        User user = new User();
        user.setValor(valor_simulado);
        
        try {
            UserDAO userDAO = new UserDAO();
            userDAO.inserirValorParaUsuario(valor_simulado, userCampo);
            
            valorSimular_campo.setText(null);
            this.dispose();
            
            RendaFixa rfx = new RendaFixa();
            rfx.setValorInvestido(valor_simulado);
            JOptionPane.showMessageDialog(null, rfx.mostrarInvestimento(), "INFORMAÇÕES DO INVESTIMENTO", JOptionPane.INFORMATION_MESSAGE);
            
            RendaVariavel rv = new RendaVariavel();
            rv.setValorInvestido(valor_simulado);
            JOptionPane.showMessageDialog(null, rv.mostrarInvestimento(), "INFORMAÇÕES DO INVESTIMENTO", JOptionPane.INFORMATION_MESSAGE);
            
            RendaVariavelUSA rvUSA = new RendaVariavelUSA();
            rvUSA.setValorInvestido(valor_simulado);
            JOptionPane.showMessageDialog(null, rvUSA.mostrarInvestimento(), "INFORMAÇÕES DO INVESTIMENTO", JOptionPane.INFORMATION_MESSAGE);
            
            Bitcoin btc = new Bitcoin();
            btc.setValorInvestido(valor_simulado);
            JOptionPane.showMessageDialog(null, btc.mostrarInvestimento(), "INFORMAÇÕES DO INVESTIMENTO", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Valor incorreto", "AVISO", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_simular_botaoActionPerformed

    private void userName_campoSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userName_campoSimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userName_campoSimActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton simular_botao;
    private javax.swing.JTextField userName_campoSim;
    private javax.swing.JTextField valorSimular_campo;
    // End of variables declaration//GEN-END:variables
}
